Neos:
  Fusion:
    defaultContext:
      'Onedrop.SectionMenu.Section': 'Onedrop\SectionMenu\EelHelper\SectionHelper'
  Neos:
    fusion:
      autoInclude:
        'Onedrop.SectionMenu': true
    userInterface:
      translation:
        autoInclude:
          'Onedrop.SectionMenu': ['NodeTypes/*']
